### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by sanketbakshi** [Microsoft/dotnet-apiport#717] opened 2018-10-17 15:25 UTC
I am getting the following error when trying to run the Portability Analyzer in VS2017. The following gets written in the Output window

An unknown error occured.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ApiPortVS.OutputWindowWriter.ClearWindowAsync()
   at ApiPortVS.AnalyzeMenu.<WriteHeaderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__7.MoveNext()

**Comment by conniey** [comment] 2018-10-17 17:18
@sanketbakshi Can you copy the Visual Studio version information by going to the "Help" menu "About Visual Studio" and "Copy Info?"

Thanks!

**Comment by conniey** [comment] 2018-11-08 12:17
Closing because there isn't enough information to reproduce this issue.

I can see it working on Visual Studio 2017, version 15.8.9.

**Closed by conniey** 2018-11-08 12:17 UTC
