### ISSUE TITLE
Offline mode fails if the output type is not specified

### ISSUE THREAD

**Issue by jeffschwMSFT** [Microsoft/dotnet-apiport#230] opened 2016-01-13 00:43 UTC
Repo:
ApiPort.offline.exe -f YourAssembly.dll -o YourAssembly.json

Sending data to service                           [Failed]
ApiPort.exe Error: 0 : System.AggregateException: One or more errors occurred. -
--> System.IO.FileNotFoundException: Could not load file or assembly 'RazorEngin
e, Version=3.6.1.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a' or one of
its dependencies. The system cannot find the file specified.
 
Workaround:
ApiPort.offline.exe -f YourAssembly.dll -o YourAssembly.json -r json

Works as expected

**Comment by mjrousos** [comment] 2016-01-13 00:53
If you don't specify an output type, I think ApiPort.offline defaults to html (by design). It seems that what's happening here is that the HTML report writer is running into some sort of issue with razor generation.

**Comment by twsouthwick** [comment] 2016-01-15 14:53
The build server drops don't have RazorEngine copied to the offline drop. If I run build.cmd locally it gets copied okay. @conniey knows more about the builds for this

**Comment by conniey** [comment] 2016-02-03 20:12
This issue was because our build server had an outdated version of `ResolveNuGetPackageAssets` task. I've updated the server. It's fixed now. :)

**Closed by conniey** 2016-02-03 20:12 UTC
Labels: bug
