### ISSUE TITLE
Have apiport allow passing a package name / version and have it automatically pull it down to analyze it and its dependencies

### ISSUE THREAD

**Issue by glennblock** [Microsoft/dotnet-apiport#572] opened 2018-02-18 15:39 UTC
Currently I can point apiport to a project and a directory. It would be helpful to also be able to give it a package name / version (and source) and have it go and pull down the package and analyze it and its dependencies.

This would be useful when trying to determine quickly if a package is compatible.

**Comment by conniey** [comment] 2019-01-08 09:50
duplicate of #450

**Closed by conniey** 2019-01-08 09:50 UTC
Labels: enhancement
