### ISSUE TITLE
Extension fails to install with error System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.Setup.Installer.VsixInstaller..ctor(System.IServiceProvider)'.

### ISSUE THREAD

**Issue by zendu** [microsoft/dotnet-apiport#859] opened 2020-03-12 20:36 UTC
I have following versions of VS installed on my machine:
VS 2017                 15.9.21
VS 2019                 16.4.6
VS 2019 Preview    16.5.0 Preview 5.0

Extension fails during installation. Install log is copied below.

3/12/2020 1:28:24 PM - Microsoft VSIX Installer
3/12/2020 1:28:24 PM - -------------------------------------------
3/12/2020 1:28:24 PM - vsixinstaller.exe version:
3/12/2020 1:28:24 PM - 16.6.1010
3/12/2020 1:28:24 PM - -------------------------------------------
3/12/2020 1:28:24 PM - Command line parameters:
3/12/2020 1:28:24 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:16.4.29905.134,/appidname:Microsoft Visual Studio Enterprise 2019,/culture:en-US,/noep,C:\Users\mawattam\AppData\Local\Temp\VSIXg5up5cha.vsix
3/12/2020 1:28:24 PM - -------------------------------------------
3/12/2020 1:28:24 PM - Microsoft VSIX Installer
3/12/2020 1:28:24 PM - -------------------------------------------
3/12/2020 1:28:24 PM - Initializing Install...
3/12/2020 1:28:25 PM - System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.Setup.Installer.VsixInstaller..ctor(System.IServiceProvider)'.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Lxiamail** [comment] 2020-04-10 16:59
@zendu Can you successfully install any other VS extension on your machine? From the call stack, it looks like an issue in VSInstaller, instead of ApiPort.vsix specific problem. If the issue repros when installing other VS extension as well, please report the VSinstaller issue at https://developercommunity.visualstudio.com

**Comment by zendu** [comment] 2020-04-11 17:06
I have been able to install/update other extensions with no issue.

**Comment by Lxiamail** [comment] 2020-04-13 18:06
@zendu Which version of ApiPort VS extension that you tried to install? Is it latest version from https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer?

**Comment by zendu** [comment] 2020-04-14 03:23
Yup.

**Comment by Lxiamail** [comment] 2020-04-14 17:54
@zendu I can't repro the problem on the local machine to do further investigation. From the call stack, it looks like a general VS installer problem. "System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.Setup.Installer.VsixInstaller..ctor(System.IServiceProvider)" seems indicate something is corrupted in the installer environment. I did some online search, didn't find any similar report either. We haven't heard other customer reported the same issue with over 2800 installation of this last ApiPort VS extension. We will put this issue on hold for now to see if we will get more actionable report in the future. In the meantime, can you try to download and run [ApiPort console tool](http://aka.ms/apiportdownload) to work around the issue?

**Comment by Lxiamail** [comment] 2020-05-20 23:45
Closing the issue for now. Please reopen if you find the issue is .NET Portability Analyzer vs extension specific issue.

**Closed by Lxiamail** 2020-05-20 23:45 UTC
Labels: NeedMoreInfo
