### ISSUE TITLE
Can't install with VS 2022 ENT

### ISSUE THREAD

**Issue by harrypooni** [microsoft/dotnet-apiport#1006] opened 2022-03-29 16:19 UTC
29/03/2022 17:18:55 - Microsoft VSIX Installer
29/03/2022 17:18:55 - -------------------------------------------
29/03/2022 17:18:55 - vsixinstaller.exe version:
29/03/2022 17:18:55 - 17.1.1035-preview2
29/03/2022 17:18:55 - -------------------------------------------
29/03/2022 17:18:55 - Command line parameters:
29/03/2022 17:18:55 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\harry.pooni\Downloads\NET Portability Analyzer v2.8.0.0.vsix
29/03/2022 17:18:55 - -------------------------------------------
29/03/2022 17:18:55 - Microsoft VSIX Installer
29/03/2022 17:18:55 - -------------------------------------------
29/03/2022 17:18:55 - Initializing Install...
29/03/2022 17:18:55 - Extension Details...
29/03/2022 17:18:55 - 	Identifier         : 55d15546-28ca-40dc-af23-dfa503e9c5fe
29/03/2022 17:18:55 - 	Name               : .NET Portability Analyzer
29/03/2022 17:18:55 - 	Author             : Microsoft
29/03/2022 17:18:55 - 	Version            : 2.8.0.0
29/03/2022 17:18:55 - 	Description        : Evaluates portability of assemblies across .NET platforms
29/03/2022 17:18:55 - 	Locale             : en-US
29/03/2022 17:18:55 - 	MoreInfoURL        : https://aka.ms/dotnet-portabilityanalyzer
29/03/2022 17:18:55 - 	InstalledByMSI     : False
29/03/2022 17:18:55 - 	SupportedFrameworkVersionRange : [4.6,)
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - 	SignatureState     : ValidSignature
29/03/2022 17:18:55 - 	SignedBy           : Microsoft Corporation
29/03/2022 17:18:55 - 	Certificate Info   : 
29/03/2022 17:18:55 - 		-------------------------------------------------------
29/03/2022 17:18:55 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
29/03/2022 17:18:55 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
29/03/2022 17:18:55 - 		[Serial Number] : 33000003C93EFB7FE21A3D22B30000000003C9
29/03/2022 17:18:55 - 		[Not Before]    : 15/12/2020 21:24:05
29/03/2022 17:18:55 - 		[Not After]     : 02/12/2021 21:24:05
29/03/2022 17:18:55 - 		[Thumbprint]    : E120FF932F2D4DFB59B1DA16BA7C397119E2DEBF
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - 	Supported Products : 
29/03/2022 17:18:55 - 		Microsoft.VisualStudio.Pro
29/03/2022 17:18:55 - 			Version : [15.0,17.0)
29/03/2022 17:18:55 - 			ProductArchitecture : x86
29/03/2022 17:18:55 - 		Microsoft.VisualStudio.Premium
29/03/2022 17:18:55 - 			Version : [15.0,17.0)
29/03/2022 17:18:55 - 			ProductArchitecture : x86
29/03/2022 17:18:55 - 		Microsoft.VisualStudio.Ultimate
29/03/2022 17:18:55 - 			Version : [15.0,17.0)
29/03/2022 17:18:55 - 			ProductArchitecture : x86
29/03/2022 17:18:55 - 		Microsoft.VisualStudio.Enterprise
29/03/2022 17:18:55 - 			Version : [15.0,17.0)
29/03/2022 17:18:55 - 			ProductArchitecture : x86
29/03/2022 17:18:55 - 		Microsoft.VisualStudio.Community
29/03/2022 17:18:55 - 			Version : [15.0,17.0)
29/03/2022 17:18:55 - 			ProductArchitecture : x86
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - 	References         : 
29/03/2022 17:18:55 - 	Prerequisites      : 
29/03/2022 17:18:55 - 		-------------------------------------------------------
29/03/2022 17:18:55 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
29/03/2022 17:18:55 - 		Name         : Visual Studio core editor
29/03/2022 17:18:55 - 		Version      : [15.0,)
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - 		-------------------------------------------------------
29/03/2022 17:18:55 - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
29/03/2022 17:18:55 - 		Name         : C# and Visual Basic
29/03/2022 17:18:55 - 		Version      : [15.0,)
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - Signature Details...
29/03/2022 17:18:55 - 	Extension is signed with a valid signature.
29/03/2022 17:18:55 - 
29/03/2022 17:18:55 - Searching for applicable products...
29/03/2022 17:18:55 - Found installed product - Global Location
29/03/2022 17:18:55 - Found installed product - Visual Studio Enterprise 2022
29/03/2022 17:18:55 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by skumar9602** [comment] 2022-04-19 13:34
> 29/03/2022 17:18:55 - Microsoft VSIX Installer 29/03/2022 17:18:55 - ------------------------------------------- 29/03/2022 17:18:55 - vsixinstaller.exe version: 29/03/2022 17:18:55 - 17.1.1035-preview2 29/03/2022 17:18:55 - ------------------------------------------- 29/03/2022 17:18:55 - Command line parameters: 29/03/2022 17:18:55 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\harry.pooni\Downloads\NET Portability Analyzer v2.8.0.0.vsix 29/03/2022 17:18:55 - ------------------------------------------- 29/03/2022 17:18:55 - Microsoft VSIX Installer 29/03/2022 17:18:55 - ------------------------------------------- 29/03/2022 17:18:55 - Initializing Install... 29/03/2022 17:18:55 - Extension Details... 29/03/2022 17:18:55 - Identifier : 55d15546-28ca-40dc-af23-dfa503e9c5fe 29/03/2022 17:18:55 - Name : .NET Portability Analyzer 29/03/2022 17:18:55 - Author : Microsoft 29/03/2022 17:18:55 - Version : 2.8.0.0 29/03/2022 17:18:55 - Description : Evaluates portability of assemblies across .NET platforms 29/03/2022 17:18:55 - Locale : en-US 29/03/2022 17:18:55 - MoreInfoURL : https://aka.ms/dotnet-portabilityanalyzer 29/03/2022 17:18:55 - InstalledByMSI : False 29/03/2022 17:18:55 - SupportedFrameworkVersionRange : [4.6,) 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - SignatureState : ValidSignature 29/03/2022 17:18:55 - SignedBy : Microsoft Corporation 29/03/2022 17:18:55 - Certificate Info : 29/03/2022 17:18:55 - ------------------------------------------------------- 29/03/2022 17:18:55 - [Subject] : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 29/03/2022 17:18:55 - [Issuer] : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 29/03/2022 17:18:55 - [Serial Number] : 33000003C93EFB7FE21A3D22B30000000003C9 29/03/2022 17:18:55 - [Not Before] : 15/12/2020 21:24:05 29/03/2022 17:18:55 - [Not After] : 02/12/2021 21:24:05 29/03/2022 17:18:55 - [Thumbprint] : E120FF932F2D4DFB59B1DA16BA7C397119E2DEBF 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - Supported Products : 29/03/2022 17:18:55 - Microsoft.VisualStudio.Pro 29/03/2022 17:18:55 - Version : [15.0,17.0) 29/03/2022 17:18:55 - ProductArchitecture : x86 29/03/2022 17:18:55 - Microsoft.VisualStudio.Premium 29/03/2022 17:18:55 - Version : [15.0,17.0) 29/03/2022 17:18:55 - ProductArchitecture : x86 29/03/2022 17:18:55 - Microsoft.VisualStudio.Ultimate 29/03/2022 17:18:55 - Version : [15.0,17.0) 29/03/2022 17:18:55 - ProductArchitecture : x86 29/03/2022 17:18:55 - Microsoft.VisualStudio.Enterprise 29/03/2022 17:18:55 - Version : [15.0,17.0) 29/03/2022 17:18:55 - ProductArchitecture : x86 29/03/2022 17:18:55 - Microsoft.VisualStudio.Community 29/03/2022 17:18:55 - Version : [15.0,17.0) 29/03/2022 17:18:55 - ProductArchitecture : x86 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - References : 29/03/2022 17:18:55 - Prerequisites : 29/03/2022 17:18:55 - ------------------------------------------------------- 29/03/2022 17:18:55 - Identifier : Microsoft.VisualStudio.Component.CoreEditor 29/03/2022 17:18:55 - Name : Visual Studio core editor 29/03/2022 17:18:55 - Version : [15.0,) 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - ------------------------------------------------------- 29/03/2022 17:18:55 - Identifier : Microsoft.VisualStudio.Component.Roslyn.LanguageServices 29/03/2022 17:18:55 - Name : C# and Visual Basic 29/03/2022 17:18:55 - Version : [15.0,) 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - Signature Details... 29/03/2022 17:18:55 - Extension is signed with a valid signature. 29/03/2022 17:18:55 - 29/03/2022 17:18:55 - Searching for applicable products... 29/03/2022 17:18:55 - Found installed product - Global Location 29/03/2022 17:18:55 - Found installed product - Visual Studio Enterprise 2022 29/03/2022 17:18:55 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products. at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) at VSIXInstaller.App.Initialize(Boolean isRepairSupported) at VSIXInstaller.App.Initialize() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

When we can expect for VS2022?

**Comment by LeoSimp** [comment] 2022-06-01 03:40
The same waitting for apply in VS2022

**Comment by brandonh-msft** [comment] 2022-08-10 22:54
dupe of #1002

**Closed by brandonh-msft** 2022-08-10 22:54 UTC
