### ISSUE TITLE
unknown error in VS 2015 Pro

### ISSUE THREAD

**Issue by jrlinde** [Microsoft/dotnet-apiport#300] opened 2016-05-16 18:19 UTC
Receiving an error when attempting to use the Portability Analyzer within VS 2015 Professional.  The command line utility works just fine; however, I would like to take advantage of the added capability of assembly replacement suggestions within the VS plugin.  Has anyone else run into this issue?  Any advice?
![image](https://cloud.githubusercontent.com/assets/7998793/15299153/f1ea7abc-1b57-11e6-8026-0f098c5bacc0.png)

**Comment by conniey** [comment] 2016-05-16 18:40
I was unable to reproduce this issue.  What are the target platforms you are running your analysis against? (You can check by going to Tools > Options > .NET Portability Analyzer)

Sometimes the portabilityservice has intermittent failures so it may work when you try again.

**Comment by jrlinde** [comment] 2016-05-16 19:01
My target environment is .NETCore 5.0.  I have tried to run the Portability Analyzer multiple times with different project types and continue to receive the same error.

**Comment by conniey** [comment] 2016-05-17 18:36
I am still unable to reproduce this issue:
* Would you be able to provide me with a repro?
* Does this happen on all projects you try to analyze in Visual Studio? or just certain ones?

Thanks!

**Comment by twsouthwick** [comment] 2016-10-05 17:19
@jrlinde I'm closing this now, but if you're able to provide a repro, we will investigate.

**Closed by twsouthwick** 2016-10-05 17:19 UTC
