### ISSUE TITLE
In addition to percentages provide number of errors per assembly

### ISSUE THREAD

**Issue by danroth27** [Microsoft/dotnet-apiport#153] opened 2015-09-24 19:42 UTC
If you have a small assembly the percentage can be misleading. It would be great to also show the number of errors per assembly in the generated report.

**Comment by twsouthwick** [comment] 2015-09-24 19:53
Can you give more detail? An example of what is currently displayed and what would be more helpful would be great.

**Comment by danroth27** [comment] 2015-09-25 00:47
The generated spreadsheet shows the list of assemblies analyzed and a percentage for how compatible the assembly is. But some assemblies are bigger than others. It would be useful to also show the number of errors in addition to the percentage.

**Comment by conniey** [comment] 2017-06-05 22:38
Duplicate of #103

**Closed by conniey** 2017-06-05 22:38 UTC
Labels: enhancement
