### ISSUE TITLE
Add Visual Studio 2017 Support

### ISSUE THREAD

**Issue by terrajobst** [Microsoft/dotnet-apiport#397] opened 2017-02-11 20:58 UTC
The VS extension is currently not available for VS 2017. We should add that.

**Comment by berlamont** [comment] 2017-04-19 02:51
This would be great, looking forward to when it comes out, thank you guys!

**Comment by conniey** [comment] 2017-05-03 19:08
Fixed in #411.

**Comment by xied75** [comment] 2017-05-04 11:57
When can we install it in VS2017?

**Comment by conniey** [comment] 2017-05-05 17:56
Our CI Builds are published to VSIXGallery. You can install/test it here: http://vsixgallery.com/extension/55d15546-28ca-40dc-af23-dfa503e9c5fe/

**Comment by scottsauber** [comment] 2017-05-06 02:52
@conniey  - I tried it out on 4 apps and ran into no issues.  Nice work. 👍

**Comment by conniey** [comment] 2017-05-07 19:12
@scottsauber 

> Edit: Just ran it on another project w/ ASP.NET Core on full framework and I'm getting this... should this work?

Detecting assembly references [Done]

Could not find file: 'C:<projectpath>\bin\Debug\net461\win7-x86'
No files were found to upload.

We never tested this scenario with the new .NET Core projects  :( I am working on a fix.  This is most likely caused by some logic here:  https://github.com/Microsoft/dotnet-apiport/blob/master/src/ApiPort.VisualStudio/DteProjectExtensions.cs#L49

**Comment by scottsauber** [comment] 2017-05-07 19:26
@conniey - Awesome.  Happy to retest when there's a fix.

**Comment by conniey** [comment] 2017-06-05 23:25
I'll update you on the issue when I fix #430.

**Closed by conniey** 2017-06-05 23:25 UTC

**Comment by conniey** [comment] 2017-06-08 17:26
@scottsauber Hey, I've finished that feature, and have fixed how we locate the assembly. Let me know if it this works for you. :) http://vsixgallery.com/extension/55d15546-28ca-40dc-af23-dfa503e9c5fe/

**Comment by scottsauber** [comment] 2017-06-08 18:43
@conniey  - Yep it worked!  Awesome work!  I got the PDB error that you mentioned in #430.  But I added DebugType Full to my csproj and it worked!

The only weird thing is I'm targeting the ASP.NET Core "current" train on Full Framework v4.6.1.  When I check 4.6.1 to be analyzed in the Portability Analyzer Settings, it tells me a bunch of things related to `Microsoft.Extensions.Logging` and `Microsoft.Extensions.DependencyInjection` that say those are not supported on 4.6.1.  I'm using the Microsoft.AspNetCore metapackage version 1.1.2 which is bringing in these Extensions packages.  It seems to work fine when I run it, so I'm not sure why it says it's not supported...?   AFAIK this should be supported.

Here are some examples of the messages I get in the Error List in VS:
Severity	Code	Description	Project	File	Line	Suppression State
Message		Microsoft.Extensions.Logging.DebugLoggerFactoryExtensions.AddDebug(Microsoft.Extensions.Logging.ILoggerFactory)
Not supported on .NET Framework,Version=v4.6.1	ProjectName	C:\path\Startup.cs	59	


Severity	Code	Description	Project	File	Line	Suppression State
Message		Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton``1(Microsoft.Extensions.DependencyInjection.IServiceCollection,``0)
Not supported on .NET Framework,Version=v4.6.1	ProjectName	C:\path\Startup.cs	44	


Severity	Code	Description	Project	File	Line	Suppression State
Message		Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(Microsoft.Extensions.Configuration.IConfigurationBuilder,System.String,System.Boolean)
Not supported on .NET Framework,Version=v4.6.1	ProjectName	C:\path\Startup.cs	23	



Let me know if I'm doing something wrong or if you want me to open up a new issue.

Thanks again for all your work on this!

**Comment by conniey** [comment] 2017-06-08 21:29
@scottsauber Thanks for testing it out! I was able to publish the latest bits on the VS Marketplace. :)  

Ahh, this is expected behaviour, unfortunately. The reason you're seeing this behaviour is because the API catalog we currently analyze against only contains binaries shipped by the .NET Framework team (in the dotnet/corefx) repository.  The binaries `Microsoft.Extensions.*` are considered platform extensions because they are shipped by partner teams.  

We've temporarily mitigated this for .NET Core and .NET Standard by adding targets ".NET Core + Platform Extensions" and ".NET Standard + Platform Extensions", which would include those binaries and show up as being supported on the platform.

**Comment by scottsauber** [comment] 2017-06-09 17:33
Ahhh that's what Platform Extensions means.  Gotcha - thanks.  Did the .NET Standard 2 + Platform Extensions and all my compat issues went away.

Thanks!
