### ISSUE TITLE
Do not understand report

### ISSUE THREAD

**Issue by ErikEJ** [Microsoft/dotnet-apiport#306] opened 2016-07-01 12:24 UTC
Target type .NET Framework,Version=v4.6.1 
System.String[0:,0:,0:]   
0:,0:,0:].#ctor(System.Int32,System.Int32,System.Int32)   
0:,0:,0:].Get(System.Int32,System.Int32,System.Int32)   
0:,0:,0:].Set(System.Int32,System.Int32,System.Int32,System.String)   

- what does this mean?

**Comment by twsouthwick** [comment] 2016-07-01 16:37
Do you have some sample code that generates this report? There are some known issues around multi-dimensional arrays that this may fall into.

**Comment by ErikEJ** [comment] 2016-07-01 19:15
I could share the dll??

**Comment by twsouthwick** [comment] 2016-07-01 19:22
That would be ideal so we can look at the types it's finding. My email is tasou at microsoft dot com

**Comment by twsouthwick** [comment] 2016-07-06 19:10
I took a look at the assembly @ErikEJ is using and it is the same issue as #42. Thanks for reporting - we'll see if someone can look into it. I'm going to close this issue as the other issue is the root cause.

**Closed by twsouthwick** 2016-07-06 19:10 UTC
