### ISSUE TITLE
An unexpected error was encountered while parsing the metadata for the PE file

### ISSUE THREAD

**Issue by mjsabby** [Microsoft/dotnet-apiport#479] opened 2017-09-18 05:34 UTC
> 
> This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
> Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).
> 
> To learn more about how this tool works, including the data we are collecting,
> go here - http://go.microsoft.com/fwlink/?LinkId=397652
> 
> Loading catalog                                   [Done]
> Loading breaking changes                          [Done]
> Detecting assembly references                     [Failed]
> 
> An unexpected error was encountered while parsing the metadata for the PE file located at c:\Foo.dll.
> 
> Cannot locate assembly info for System.Object

**Comment by mjsabby** [comment] 2017-09-18 05:35
Something has changed recently that broke this, I'm not sure what it is yet but ApiPort worked fine for us a few months ago.

**Comment by twsouthwick** [comment] 2017-09-18 15:41
Can you share details of how you're running this? 

- Are you using the VS extension or cli?
- Are you building it yourself or downloading it?
- Version of tool (if downloaded, or git hash if built yourself)

**Comment by conniey** [comment] 2017-09-18 15:45
From the output, 
```
Loading catalog [Done]
Loading breaking changes [Done]
```
it looks like the tool is being run in offline mode. @alinapopa was looking into fixing an issue in Offline mode?

**Comment by mjsabby** [comment] 2017-09-18 17:41
I've verified that this commit a79478eb9715b3a9fa842e939cee892d93ab37ab works fine and HEAD does not.

I built the tool myself and ran it in offline mode.

The reason I picked this commit was that the exception was coming from ComputeData which was changed after this commit.

Exception:
> Microsoft.Fx.Portability.MetadataReader!DependencyFinderEngineHelper.ComputeData
>  Microsoft.Fx.Portability.MetadataReader!ReflectionMetadataDependencyInfo.GetDependencies
>   Microsoft.Fx.Portability.MetadataReader!Microsoft.Fx.Portability.Analyzer.ReflectionMetadataDependencyInfo.<FindDependencies>b__16_0(class Microsoft.Fx.Portability.IAssemblyFile)

**Comment by alinapopa** [comment] 2017-09-18 19:12
@conniey I get an error when running ApiPort in Offline mode but it's different - it fails right at the beginning due to not loading the right version of some dependencies. It's fixed with #481 .
The error @mjsabby gets is something else. Looks like it's failing at https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability.MetadataReader/DependencyFinderEngineHelper.cs#L89
(`systemObjectAssembly` is null).

**Comment by twsouthwick** [comment] 2017-09-18 20:52
@mjsabby if the error @alinapopa is the right one, it implies we can't determine what assembly `System.Object` is located in. Is the assembly you're analyzing available for us to attempt a repro?

**Comment by ninjaboy** [comment] 2017-10-16 13:45
Same problem here.
It although shows the following:
Detecting assembly references                     [Failed]

An unexpected error was encountered while parsing the metadata for the PE file located at Debug/Owin.dll.

Microsoft.Fx.Portability.PortabilityAnalyzerException: Cannot locate assembly info for System.Object
   at Microsoft.Fx.Portability.Analyzer.DependencyFinderEngineHelper.ComputeData() in /Users/ninjaboy/Projects/dotnet/dotnet-apiport/src/Microsoft.Fx.Portability.MetadataReader/DependencyFinderEngineHelper.cs:line 93
   at Microsoft.Fx.Portability.Analyzer.ReflectionMetadataDependencyInfo.GetDependencies(IAssemblyFile file) in /Users/ninjaboy/Projects/dotnet/dotnet-apiport/src/Microsoft.Fx.Portability.MetadataReader/ReflectionMetadataDependencyInfo.cs:line 127

Cannot locate assembly info for System.Object

**Comment by twsouthwick** [comment] 2017-10-16 21:28
Thanks @ninjaboy for reporting as well. Is `Owin.dll` available for us to debug with?

**Comment by ninjaboy** [comment] 2017-10-17 11:05
Install-Package Owin -Version 1.0.0

I think the issue reproduces when I specify folder as an input for analyze. Doesn't reproduce when the specific file is passed as input for analysis

**Comment by IrisClasson** [comment] 2017-10-24 15:08
I get the same error. The previous release works fine.

**Comment by conniey** [comment] 2017-10-25 16:58
@twsouthwick I suspect it has something to do with the logic we added here: https://github.com/Microsoft/dotnet-apiport/blob/dev/src/Microsoft.Fx.Portability.MetadataReader/DependencyFinderEngineHelper.cs#L68

Do you have time to look at it? If not, I can check it out later today or tomorrow.

**Closed** 2017-11-09 00:39 UTC
Labels: bug

**Comment by rafael-teixeira** [comment] 2017-11-16 18:00
Hello,

It seems that the issue still persist, but for other reason now.

```
C:\Sources\Repos\dotnet-apiport\bin\Debug\ApiPort\net46\win7-x64>ApiPort.exe analyze -f "f:\temp.dll" -t ".NET Framework, Version=4.6.2" -b -r Html -o "C:\temp.html"
Microsoft (R) API Portability Analyzer vunknown
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting,
go here - http://go.microsoft.com/fwlink/?LinkId=397652

Detecting assembly references                     [Failed]

**An unexpected error was encountered while parsing the metadata for the PE file located at f:\temp.dll**.

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Fx.Portability.Analyzer.DependencyFinderEngineHelper.GetSystemRuntimeAssemblyInformation() in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:line 213
   at Microsoft.Fx.Portability.Analyzer.DependencyFinderEngineHelper.ComputeData() in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:line 60
   at Microsoft.Fx.Portability.Analyzer.ReflectionMetadataDependencyInfo.GetDependencies(IAssemblyFile file) in C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\ReflectionMetadataDependencyInfo.cs:line 128
```

I verified the source code and the issue is taking place in the line below

C:\Sources\Repos\dotnet-apiport\src\Microsoft.Fx.Portability.MetadataReader\DependencyFinderEngineHelper.cs:213

`
var matchingAssembly = microsoftAssemblies.SingleOrDefault(x => s_systemObjectAssemblies.Contains(x.Name));`

microsoftAssemblies collection has duplicated assembly names that causes exception on SingleOrDefault() method as below: 

```
{System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
{mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}	Microsoft.Fx.Portability.ObjectModel.AssemblyReferenceInformation
```

**Comment by conniey** [comment] 2017-11-16 18:20
@rafael-teixeira Can you create a new issue for this? It is different than what this issue is. Also, can you provide a repro for this? I'm not sure how it is possible that you can reference both versions of mscorlib from a single assembly.

**Comment by rafael-teixeira** [comment] 2017-11-17 11:12
@conniey, yes for sure. I'll do it. Thanks!

**Comment by silentnightwalk** [comment] 2018-08-16 13:51
Get the same error:
Downloaded Apiport from here:
https://blogs.msdn.microsoft.com/dotnet/2018/08/08/are-your-windows-forms-and-wpf-applications-ready-for-net-core-3-0/?utm_source=vs_developer_news&utm_medium=referral
(It goes with the winforms ui app).
Any help appreciated.
