### ISSUE TITLE
DGML generation seems to be broken

### ISSUE THREAD

**Issue by vruss** [microsoft/dotnet-apiport#923] opened 2020-09-18 09:23 UTC
While trying to generate DGML output of a very large BuildOutput of assemblies I receive different error codes

ApiPort.2.7.0 Run from Windows Powershell:
```ps1
.\ApiPort.exe analyze -f .\source\BuildOutput -t ".NET Standard, Version=1.3" -r DGML -o DependencyReport_Standard1.3.dgml
```

#### Error codes
first run:
```
There was an unexpected error.  Please try again or contact apiport@microsoft.com for help.
```
Once:
```
There was an unknown error code from the service: 'BadGateway'.  Please make sure you have the most up-to-date version.
```
Several:
```
There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
```

Edit: I re-ran with Excel output and it worked this time. DGML still broken.

**Comment by Lxiamail** [comment] 2020-09-28 17:51
@vruss Thanks for reporting the issue. Does the same issue repro if analyze smaller binary?

**Comment by ardalis** [comment] 2020-10-25 22:22
I'm getting this now when I run this on this repo:
https://github.com/dotnet-architecture/eShopModernizing/tree/master/eShopLegacyMVCSolution

Using latest version downloaded today and VS2019.

**Comment by raydixon** [comment] 2020-12-01 03:22
This looks like a duplicate of #896

**Comment by aszalacinski** [comment] 2021-01-15 20:48
Is there an update on this issue?

**Closed** 2022-11-15 23:32 UTC

**Comment by terrajobst** [comment] 2022-11-15 23:37
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
