### ISSUE TITLE
Consider including the number of usages of each API in the portability score

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/dotnet-apiport#233] opened 2016-01-15 18:46 UTC
The portability score reported by APIPort is based on the number of distinct APIs used by the assembly being analyzed.  This means that an unsupported API that is used 1000 times has the same effect on the score as one that's only used once.  It also means that if you remove 999 usages of an unsupported API, but there's one left over, the portability score won't change at all.

It would probably be more useful if it reported a score based on the number of times each API was used in the assembly.

**Comment by conniey** [comment] 2016-02-04 20:39
Duplicate of #103

**Closed** 2016-02-04 20:40 UTC
Labels: enhancement
