### ISSUE TITLE
500 Internal server error when trying to run portability analysis and generate DGML

### ISSUE THREAD

**Issue by lxman** [microsoft/dotnet-apiport#955] opened 2020-12-03 16:06 UTC
Trying to run analysis against a 4.7.2 winforms project checking for .NET 5 and trying to generate DGML. Unchecking the DGML option allows it to work. Unfortunately the project is closed source, so will not be able to provide repro in this instance.

**Comment by rsabirov** [comment] 2021-03-01 11:50
Duplicate of #896

**Comment by Lxiamail** [comment] 2021-03-01 18:59
Yes, it's known issue. Close this issue and use #896  to track it.

**Closed by Lxiamail** 2021-03-01 18:59 UTC
