### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by JerkerPihl** [Microsoft/dotnet-apiport#600] opened 2018-04-05 13:30 UTC
Testing on an old solution with old projects (.NET 4.6.1 )

An unknown error occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApiPortVS.DefaultProjectBuilder.<GetBuildOutputFilesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.VS2015.ProjectBuilder2015.<GetBuildOutputFilesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ApiPortVS.Analyze.ProjectAnalyzer.<AnalyzeProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiPortVS.AnalyzeMenu.<AnalyzeProjectsAsync>d__6.MoveNext()

**Comment by twsouthwick** [comment] 2018-12-18 04:00
This looks to be a duplicate of #601. If it's not, please give more information (ie a sample `.dll` or source we can test with)

**Closed by twsouthwick** 2018-12-18 04:00 UTC
Labels: bug, client-side
