### ISSUE TITLE
Type.IsAssignableFrom reported to be "Not Supported"

### ISSUE THREAD

**Issue by AArnott** [Microsoft/dotnet-apiport#399] opened 2017-02-27 15:32 UTC
[According to `apisof.net`](https://apisof.net/catalog/System.Type.IsAssignableFrom(Type)), `Type.IsAssignableFrom(Type)` is available in netstandard2.0. But this command line tool says it's simply "Not supported".

**Comment by chlowell** [comment] 2017-02-27 17:46
`apisof.net` is correct here. However, when no target netstandard version is specified, ApiPort defaults to 1.6. For it to consider APIs in 2.0, that version must be specified: `ApiPort.exe analyze -t ".NET Standard,Version=2.0"`.

Even so, instead of labeling the API "Not supported", the Excel report should indicate its availability in netstandard2.0.

**Comment by AArnott** [comment] 2017-02-27 17:48
This answer seems to suggest that no API available only in netstandard2.0 will be reported as available in the spreadsheet. But in fact that's not the case. When I use `-t ".NET Standard"`, I see APIs that are simply "not supported" as well as APIs that are available only in .netstandard2.0:

![image](https://cloud.githubusercontent.com/assets/3548/23372761/dd2a36b0-fcd1-11e6-94cd-3adc77b64f5b.png)

**Comment by chlowell** [comment] 2017-02-27 17:50
Sorry if I was unclear above--I agree the inconsistency is a bug; the report should indicate support in 2.0+.

**Comment by twsouthwick** [comment] 2017-05-25 14:53
This probably has a similar root cause as https://github.com/Microsoft/dotnet-apiport/issues/113

**Comment by conniey** [comment] 2017-06-05 23:26
Duplicate of #113

**Closed by conniey** 2017-06-05 23:26 UTC
