### ISSUE TITLE
Issues choosing .NET Core target in VS extension of the tool

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/dotnet-apiport#310] opened 2016-07-14 19:32 UTC
Somehow .NET Core (v5.0) is not being detected as a supported target. I was able to run this from the VS Extension couple of days back but something seems to be broken. I'm able to target other platforms.

Here is the Output:
Finding source line information
	Microsoft.Azure.Documents.Client.dll           [Done]
Microsoft (R) .NET Portability Analyzer 1.0.261.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
Sending data to service                            [Failed]

Unknown target '.NET Core,Version=v5.0'

**Comment by twsouthwick** [comment] 2016-07-15 19:41
Thanks, @rnagpal. This is a known issue that @conniey is looking into.

**Comment by conniey** [comment] 2016-07-25 15:59
@rnagpal I am working on a fix for this. The problem is that the extension is not updating the targets properly when they have been saved. As a workaround, you can:

1. Close Visual Studio
2. Go to the folder: `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\Extensions`\
    * For me, it was inside `AppData\Local\Microsoft\VisualStudio\14.0\Extensions\le3cm214.ez2`
3. Inside, search for: `options.dat` and delete it
4. Reopen Visual Studio

The targets should refresh again.

**Comment by twsouthwick** [comment] 2016-10-05 17:39
This is fixed and will be available in the next release.

**Closed by twsouthwick** 2016-10-05 17:39 UTC
Labels: bug
