### ISSUE TITLE
"Could not find file: '<projectpath>\bin\Debug\net46\' from VSIX

### ISSUE THREAD

**Issue by GeekActual** [Microsoft/dotnet-apiport#429] opened 2017-05-22 16:06 UTC
I have a simple project that I have built and compiled in 4.6. I have confirmed that the complied .dll is available in <projectpath>\bin\Debug\net46\ directory . 

Downloaded and installed vsix for portability tool, in Visual Studio 2017.  When I attempt to run the addin I always get the following error with no other information provided.

```
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
* Could not find file: 'C:\src\acme\tfs\Core\Acme.Core\bin\Debug\net46\'
* No files were found to upload.

Finding source line information
                                                                    [Failed]
```

**Comment by conniey** [comment] 2017-05-22 19:17
What is the project type you are using? Is it one of the new [csproj](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/csproj) that have the `Microsoft.NET.Sdk` project imports?

**Comment by GeekActual** [comment] 2017-05-24 19:14
No it is not, that's why I'm trying to run the upgrade Advisor utility.

It works if I use the analyze function from the toolbar that lets you select a single dollar to analyze, but not if I use the right mouse click function in the solution Explorer

Matthew

e pluribus unum




On Mon, May 22, 2017 at 3:17 PM -0400, "Connie Yau" <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the project type you are using? Is it one of the new csproj<https://docs.microsoft.com/en-us/dotnet/articles/core/tools/csproj> that have the Microsoft.NET.Sdk project imports?

**Comment by conniey** [comment] 2017-06-05 23:36
Duplicate of #430

**Closed by conniey** 2017-06-05 23:36 UTC
Labels: bug
